# Generated by Django 3.2.3 on 2021-05-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='Title')),
                ('Text', models.TextField(verbose_name='Text')),
                ('Data', models.FileField(blank=True, null=True, upload_to='', verbose_name='Data')),
                ('Ord', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ord')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='Title')),
                ('ReadableUser', models.ManyToManyField(related_name='ReadableUser', to=settings.AUTH_USER_MODEL)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.content')),
                ('Graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('EndNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EndNode', to='base.node')),
                ('StartNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StartNode', to='base.node')),
            ],
        ),
    ]
