# Generated by Django 3.2.3 on 2021-05-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='IsBase',
            field=models.BooleanField(default=False, verbose_name='IsBase'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
