# Generated by Django 3.2.3 on 2021-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210530_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Ord',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ord'),
        ),
    ]
