# Generated by Django 3.2.3 on 2021-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_content_ord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='Weight',
            field=models.IntegerField(default=0, verbose_name='Weight'),
        ),
    ]
