# Generated by Django 3.2.3 on 2021-06-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_link_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Ord',
            field=models.IntegerField(default=0, verbose_name='Ord'),
        ),
        migrations.AlterField(
            model_name='token',
            name='UUID',
            field=models.UUIDField(unique=True, verbose_name='Token'),
        ),
    ]
